# Generated by Django 4.2.23 on 2025-09-01 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0005_auto_20250825_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsocial',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redsocial',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='redsocial',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
