# Generated by Django 4.2.23 on 2025-09-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_remove_cliente_precio_plan_remove_cliente_sector_and_more'),
        ('planes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, to='planes_app.plan')),
            ],
            options={
                'verbose_name': 'Plan del Cliente',
                'verbose_name_plural': 'Planes de Clientes',
                'db_table': 'clientes_planes',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('id_cliente', 'id_plan', 'estado')},
            },
        ),
    ]
