# Generated by Django 4.2.23 on 2026-03-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Última actividad del usuario para timeout de sesión', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='session_timeout_minutes',
            field=models.IntegerField(default=30, help_text='Tiempo de expire de sesión en minutos'),
        ),
    ]
