# Generated by Django 4.2.23 on 2025-09-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectores_app', '0001_initial'),
        ('clientes', '0002_alter_cliente_apellidos_alter_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='precio_plan',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_plan',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_sector',
            field=models.ForeignKey(blank=True, db_column='id_sector', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectores_app.sector'),
        ),
    ]
